### ISSUE TITLE
clarify expected compatibility with DSM 5 and x14 hardware series

### ISSUE THREAD

**Issue by ssbarnea** [hsleep/ds213j_bootstrap#2]
I do hava a DSM 214+ which has this CPU and I don't know if this bootstrap is supposed to work or not. 

Based on what I read, it should, and if that's true please add this information to the readme, I am sure there a MANY others looking for the same thing. Thanks.

```
Processor	: Marvell PJ4Bv7 Processor rev 2 (v7l)
processor	: 0
BogoMIPS	: 1332.01

processor	: 1
BogoMIPS	: 1332.01

Features	: swp half thumb fastmult vfp edsp vfpv3 tls
CPU implementer	: 0x56
CPU architecture: 7
CPU variant	: 0x2
CPU part	: 0x584
CPU revision	: 2

Hardware	: Marvell Armada XP Development Board
```

**Comment by hsleep** [comment]
sorry, @ssbarnea too late response.

If you want, test on another model. clone this repository and change `bootstrap.sh` line 21.

```
if ! grep Armada-370 /proc/cpuinfo >/dev/null 2>&1; then
    echo "Error: CPU not Marvell Armada-370, probably wrong bootstrap.xsh"
    exit 3
fi
```

change `Armada-370` to `your own model` and run `makexsh.sh`.
And copy `syno-mvam-bootstrap_1.2-7_arm_ds213j.xsh` to you NAS and run it.

Thank you.
